global:
  scrape_interval: 15s # How frequently to scrape targets by default.

scrape_configs:
  # Scrape metrics from Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['0.0.0.0:9090']

  # Scrape metrics from Node Exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['0.0.0.0:9100'] # 'node_exporter' is the service name from docker-compose
  - job_name: 'poglytics_scrapper'
    static_configs:
      - targets: ['0.0.0.0:9091'] # Assuming the scrapper exposes metrics on port
